version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jenkins-ec2
    container_name: jenkins-ec2
    ports:
      - "8005:8005"
    networks:
      - jenkins
    volumes:
      - ./:/app
    env_file:
      - .env
    restart: unless-stopped
networks:
  jenkins:
    external: true
